### ISSUE TITLE
Keep getting "Server Disconnected" error. Baremetal Cloudera setup.

### ISSUE THREAD

**Issue by vijay-jangir** [dataflint/spark#8] opened 2024-03-11 14:36 UTC
**Describe the bug**
Dataflint tab in spark UI keeps giving server disconnected, and then it refreshes, 
it also doesn't show spark sql queries (ongoing or completed) and keeps saying that no spark sql query

**Environemnt**
spark verison: 3.2
platform: standalone/ cloudera

**To Reproduce**
1. Go to DataFlint tab

it will keep showing server disconnected, then it'll refresh and show the page for a few moments, and then again it'll say server disconnected.

**Expected behavior**
2 expectations,
-  for whatever reason, if server disconnected, i should be able to view existing data if possible. 
- if the job is running, and spark ui is working fine, then dataflint shoudln't show server disocnnected.

**Screenshots**
<img width="1197" alt="image" src="https://github.com/dataflint/spark/assets/6284383/f751f859-31d9-446f-b219-41c0be9d4a78">

**Additional context**

**Comment by menishmueli** [comment] 2024-03-11 14:47
Hi @vijay-jangir!
Can you please open the inspect window in your web browser and share a screenshot of the console & network tab?

**Comment by menishmueli** [comment] 2024-03-11 14:51
We could also discuss it in the support channel in the DataFlint slack community https://join.slack.com/t/dataflint/shared_invite/zt-28sr3r3pf-Td_mLx~0Ss6D1t0EJb8CNA

**Comment by vijay-jangir** [comment] 2024-03-13 09:31
getting below error in console logs
`dataflint/:2 
        
        
       GET http://p1vl-pa-nnrm01.india.airtel.itm:8088/proxy/application_1706528882986_6823/api/v1/applications/application_1706528882986_6823/1/sql?offset=0&length=1000&planDescription=false 500 (Server Error)
(anonymous) @ dataflint/:2
u @ dataflint/:2
(anonymous) @ dataflint/:2
(anonymous) @ dataflint/:2
be @ dataflint/:2
o @ dataflint/:2
(anonymous) @ dataflint/:2
(anonymous) @ dataflint/:2
(anonymous) @ dataflint/:2
(anonymous) @ dataflint/:2
u @ dataflint/:2
(anonymous) @ dataflint/:2
(anonymous) @ dataflint/:2
be @ dataflint/:2
o @ dataflint/:2
Promise.then (async)
be @ dataflint/:2
o @ dataflint/:2
Promise.then (async)
be @ dataflint/:2
o @ dataflint/:2
Promise.then (async)
be @ dataflint/:2
o @ dataflint/:2
Promise.then (async)
be @ dataflint/:2
o @ dataflint/:2
Promise.then (async)
be @ dataflint/:2
o @ dataflint/:2
Promise.then (async)
be @ dataflint/:2
o @ dataflint/:2
(anonymous) @ dataflint/:2
(anonymous) @ dataflint/:2
(anonymous) @ dataflint/:2
setTimeout (async)
(anonymous) @ dataflint/:2
u @ dataflint/:2
(anonymous) @ dataflint/:2
(anonymous) @ dataflint/:2
be @ dataflint/:2
s @ dataflint/:2
Promise.then (async)
be @ dataflint/:2
o @ dataflint/:2
Promise.then (async)
be @ dataflint/:2
o @ dataflint/:2
Promise.then (async)
be @ dataflint/:2
o @ dataflint/:2
Promise.then (async)
be @ dataflint/:2
o @ dataflint/:2
Promise.then (async)
be @ dataflint/:2
o @ dataflint/:2
Promise.then (async)
be @ dataflint/:2
o @ dataflint/:2
Promise.then (async)
be @ dataflint/:2
o @ dataflint/:2
(anonymous) @ dataflint/:2
(anonymous) @ dataflint/:2
(anonymous) @ dataflint/:2
setTimeout (async)
(anonymous) @ dataflint/:2
u @ dataflint/:2
(anonymous) @ dataflint/:2
(anonymous) @ dataflint/:2
be @ dataflint/:2
s @ dataflint/:2
Promise.then (async)
be @ dataflint/:2
o @ dataflint/:2
Promise.then (async)
be @ dataflint/:2
o @ dataflint/:2
Promise.then (async)
be @ dataflint/:2
o @ dataflint/:2
Promise.then (async)
be @ dataflint/:2
o @ dataflint/:2
Promise.then (async)
be @ dataflint/:2
o @ dataflint/:2
Promise.then (async)
be @ dataflint/:2
o @ dataflint/:2
Promise.then (async)
be @ dataflint/:2
o @ dataflint/:2
(anonymous) @ dataflint/:2
(anonymous) @ dataflint/:2
(anonymous) @ dataflint/:2
setTimeout (async)
(anonymous) @ dataflint/:2
u @ dataflint/:2
(anonymous) @ dataflint/:2
(anonymous) @ dataflint/:2
be @ dataflint/:2
s @ dataflint/:2
Promise.then (async)
be @ dataflint/:2
o @ dataflint/:2
Promise.then (async)
be @ dataflint/:2
o @ dataflint/:2
Promise.then (async)
be @ dataflint/:2
o @ dataflint/:2
Promise.then (async)
be @ dataflint/:2
o @ dataflint/:2
Promise.then (async)
be @ dataflint/:2
o @ dataflint/:2
Promise.then (async)
be @ dataflint/:2
o @ dataflint/:2
Promise.then (async)
be @ dataflint/:2
o @ dataflint/:2
(anonymous) @ dataflint/:2
(anonymous) @ dataflint/:2
(anonymous) @ dataflint/:2
setTimeout (async)
(anonymous) @ dataflint/:2
u @ dataflint/:2
(anonymous) @ dataflint/:2
(anonymous) @ dataflint/:2
be @ dataflint/:2
s @ dataflint/:2
Promise.then (async)
be @ dataflint/:2
o @ dataflint/:2
dataflint/:2 request to path: http://p1vl-pa-nnrm01.india.airtel.itm:8088/proxy/application_1706528882986_6823/api/v1/applications/application_1706528882986_6823/1/sql?offset=0&length=1000&planDescription=false failed, error: SyntaxError: Unexpected token '<', "<html>
<he"... is not valid JSON
dataflint/:2 SyntaxError: Unexpected token '<', "<html>
<he"... is not valid JSON`

network screenshot

**Comment by menishmueli** [comment] 2024-03-13 09:57
So the 500 error you are getting is from a request to Spark official REST API (meaning the issue is on Spark side, not DataFlint):
![image](https://github.com/dataflint/spark/assets/11976579/934d2fcd-7efd-401f-b4c4-95fec9502c0d)
(https://spark.apache.org/docs/latest/monitoring.html)

I got multiple reports so far for this errors specifically in spark 3.2, so I would suggest if possible to upgrade your spark version. 
I don't think the issue is related to Cloudera as I know of Cloudera users that managed to install DataFlint successfully.

Also, if you could share the error log from Spark driver that lead to this 500 error, it might help me to add some kind of walkaround for this Spark 3.2 issue.

**Comment by vijay-jangir** [comment] 2024-03-15 04:35
same issue with different spark. can you share the thread/info of users who use this with cloudera? i'll try to replicate my setup.
also no issue in spark
to me it looks like a yarn issue, looking into this

**Comment by vijay-jangir** [comment] 2024-03-15 05:43
opened  #9 for this
also, the npm run format seems to chagne alot of files, so i've not done that before push.

**Comment by vijay-jangir** [comment] 2024-03-15 06:25
Caused by: org.glassfish.jersey.server.ContainerException: com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: scala.collection.convert.Wrappers$IterableWrapper[1])
	at org.glassfish.jersey.servlet.internal.ResponseWriter.rethrow(ResponseWriter.java:254)
	at org.glassfish.jersey.servlet.internal.ResponseWriter.failure(ResponseWriter.java:236)
	at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:438)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:263)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
	... 39 more
Caused by: com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: scala.collection.convert.Wrappers$IterableWrapper[1])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:397)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:368)
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:338)

**Comment by vijay-jangir** [comment] 2024-03-15 06:29
another finding, this works fine in client mode, only gives this error in cluster mode

**Comment by vijay-jangir** [comment] 2024-03-15 08:01
so the issue is only with applications using spring dependency injection framework. apart from that it's working fine,

**Comment by menishmueli** [comment] 2024-03-15 10:28
Interesting, my best guess it's some kind of dependency issue relates to jackson, where you have a jackson version incompatible with what's spark expect.

Anyway the exception stack doesn't help much to detect what is the issue. So if it's currently working I'm closing this issue.

If you have any more issues or have feedback/feature ideas/interesting use cases please contact me at the slack community at any time!

**Closed by menishmueli** 2024-03-15 10:28 UTC
